OUTDIR = config["outdir"]
FASTA = config["fasta"]
EXECUTION_FOLDER = config['execution_folder']
BUSCO_LINEAGE = config['busco_lineage']
MODE = config["mode"]
PREFIX = config["prefix"]
TMP_OUTDIR = config["tmp_outdir"]

rule all:
    input:
        busco_stats = f"{OUTDIR}/{PREFIX}.busco", 

rule envs:
    input:
        busco = "../envs/busco.yaml"

envs = rules.envs.input 

include: "./rules/busco.smk"